{
 "title": "Metrics Utilization",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "source", "label": "Datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  { "title": "$source // Unique Time Series", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }, "repeat": "source" },
  {
   "title": "Current Unique Time Series",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(logzio_metrics_current_unique_time_series)"
    }
   ]
  },
  {
   "title": "Unique Time Series - Current VS Allowed ",
   "type": "timeseries",
   "gridPos": { "h": 16, "w": 13, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(logzio_metrics_current_unique_time_series)",
     "legendFormat": "Current Unique Time Series"
    },
    {
     "expr": "sum(logzio_metrics_allowed_unique_time_series)",
     "legendFormat": "Allowed Unique Time Series"
    }
   ]
  },
  {
   "title": "Highest Cardinality Metrics Right Now",
   "type": "bargauge",
   "description": "These are the metrics who generate the most unique time series, as of this moment.\nMetrics who generate a lot of unique time series has many labels and label values combinations.",
   "gridPos": { "h": 16, "w": 7, "x": 17, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(10, count by (__name__)({__name__=~\".+\"}))"
    }
   ]
  },
  {
   "title": "Current Unique Time Series Utilization",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(logzio_metrics_current_unique_time_series)/sum(logzio_metrics_allowed_unique_time_series)"
    }
   ]
  },
  { "title": "$source // Data Points", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 85 }, "repeat": "source" },
  {
   "title": "Shipped Data Points",
   "type": "stat",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 86 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(logzio_metrics_shipped_data_points_per_minute)"
    }
   ]
  },
  {
   "title": "Accepted Data Points",
   "type": "stat",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 86 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(logzio_metrics_accepted_data_points_per_minute)"
    }
   ]
  },
  {
   "title": "Dropped Data Points",
   "type": "stat",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 86 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(logzio_metrics_dropped_data_points_per_minute)"
    }
   ]
  },
  {
   "title": "Data Points Utilization - Accepted Vs Allowed",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 92 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(logzio_metrics_accepted_data_points_per_minute)/sum(logzio_metrics_allowed_data_points_per_minute)"
    }
   ]
  },
  {
   "title": "Data Points Shipping - Accepted Vs Shipped",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 92 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(logzio_metrics_accepted_data_points_per_minute)/sum(logzio_metrics_shipped_data_points_per_minute)"
    }
   ]
  },
  {
   "title": "Data Points Shipping - Dropped Vs Shipped",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 92 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(logzio_metrics_dropped_data_points_per_minute)/sum(logzio_metrics_shipped_data_points_per_minute)"
    }
   ]
  },
  {
   "title": "Data Points Stats Over Time",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 98 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(logzio_metrics_accepted_data_points_per_minute)",
     "legendFormat": "Accepted Data Points"
    },
    {
     "expr": "sum(logzio_metrics_allowed_data_points_per_minute)",
     "legendFormat": "Allowed Data Points"
    },
    {
     "expr": "sum(logzio_metrics_dropped_data_points_per_minute)",
     "legendFormat": "Dropped Data Points"
    }
   ]
  }
 ]
}